Repository DICOMANON/DPHIANT, pull requests merged in 2021-12, with the labels that each got.

#57 amend initial setup/install to README.md
  README.md
Labels: task

#59 Automation code
  dicomFiles/anonymized1-MR-1-instance/MR000000.dcm
  dicomFiles/anonymized2-MR-1-instance/MR000000.dcm
  dicomFiles/source.dcm
  test-demo.py
Labels: feature

#60 Create Peer Testing Report 1.pdf
  Peer Testing #1/Peer Testing #1 Script.pdf
  Peer Testing #1/Peer Testing Report 1.pdf
Labels: chore
